import type { NewCharacterSchemaType } from '../../src/schema/characters'

export const characters: (NewCharacterSchemaType & {
  conditions: undefined
  currentHp: number | null
  tempHp: number | null
  currentAc: number | null
  deathSavesSuccess: number | null
  deathSavesFailed: number | null
})[] = [
  {
    // id: 'cl6zs8qg10910y6s64qb2bu2w',
    name: 'Cora Hilltopple',
    playerName: 'Kate',
    // createdById: 'cl5or5v160006uts6oqve5l5a',
    // createdAt: '2022-08-19T01:18:12.961Z',
    // updatedAt: '2022-08-19T01:18:12.962Z',
    type: 'pc',
    isFriendly: false,
    isDead: false,
    avatar: '',
    race: 'Halfing',
    characterClass: 'Rogue',
    subclass: 'Lightfoot',
    advancementType: 'xp',
    level: 6,
    experiencePoints: 0,
    hpMax: 39,
    ac: 16,
    spellSave: 0,
    hitDice: null,
    conditions: undefined,
    currentHp: null,
    tempHp: null,
    currentAc: null,
    deathSavesSuccess: null,
    deathSavesFailed: null,
    initiative: 0,
    inspiration: false,
    speedWalking: 25,
    speedClimbing: 0,
    speedFlying: 0,
    speedSwimming: 0,
    speedBurrowing: 0,
    creatureSize: '',
    creatureType: '',
    alignment: '',
    challengeRating: '',
    source: '',
    str: 8,
    strBonus: false,
    dex: 18,
    dexBonus: true,
    con: 12,
    conBonus: false,
    int: 13,
    intBonus: true,
    wis: 10,
    wisBonus: false,
    cha: 16,
    chaBonus: false,
    skillAcrobaticsProficient: true,
    skillAcrobaticsExpertise: false,
    skillAnimalHandlingProficient: false,
    skillAnimalHandlingExpertise: false,
    skillArcanaProficient: false,
    skillArcanaExpertise: false,
    skillAthleticsProficient: false,
    skillAthleticsExpertise: false,
    skillDeceptionProficient: true,
    skillDeceptionExpertise: false,
    skillHistoryProficient: false,
    skillHistoryExpertise: false,
    skillInsightProficient: false,
    skillInsightExpertise: false,
    skillIntimidationProficient: false,
    skillIntimidationExpertise: false,
    skillInvestigationProficient: true,
    skillInvestigationExpertise: false,
    skillMedicineProficient: false,
    skillMedicineExpertise: false,
    skillNatureProficient: false,
    skillNatureExpertise: false,
    skillPerceptionProficient: false,
    skillPerceptionExpertise: false,
    skillPerformanceProficient: true,
    skillPerformanceExpertise: false,
    skillPersuasionProficient: false,
    skillPersuasionExpertise: false,
    skillReligionProficient: false,
    skillReligionExpertise: false,
    skillSleightOfHandProficient: true,
    skillSleightOfHandExpertise: false,
    skillStealthProficient: true,
    skillStealthExpertise: false,
    skillSurvivalProficient: false,
    skillSurvivalExpertise: false,
  },
  {
    // id: 'cl6zsag5b0955y6s6kv0zo2r9',
    name: 'Edwin Toddsbreath',
    playerName: 'Russ',
    // createdById: 'cl5or5v160006uts6oqve5l5a',
    // createdAt: '2022-08-19T01:19:32.927Z',
    // updatedAt: '2022-08-19T01:19:32.928Z',
    type: 'pc',
    isFriendly: false,
    isDead: false,
    avatar: '',
    race: 'Human',
    characterClass: 'Fighter',
    subclass: '',
    advancementType: 'xp',
    level: 6,
    experiencePoints: 0,
    hpMax: 52,
    ac: 17,
    spellSave: 0,
    hitDice: null,
    conditions: undefined,
    currentHp: null,
    tempHp: null,
    currentAc: null,
    deathSavesSuccess: null,
    deathSavesFailed: null,
    initiative: 0,
    inspiration: false,
    speedWalking: 30,
    speedClimbing: 0,
    speedFlying: 0,
    speedSwimming: 0,
    speedBurrowing: 0,
    creatureSize: '',
    creatureType: '',
    alignment: '',
    challengeRating: '',
    source: '',
    str: 15,
    strBonus: true,
    dex: 16,
    dexBonus: false,
    con: 15,
    conBonus: true,
    int: 11,
    intBonus: false,
    wis: 13,
    wisBonus: false,
    cha: 10,
    chaBonus: false,
    skillAcrobaticsProficient: false,
    skillAcrobaticsExpertise: false,
    skillAnimalHandlingProficient: true,
    skillAnimalHandlingExpertise: false,
    skillArcanaProficient: false,
    skillArcanaExpertise: false,
    skillAthleticsProficient: false,
    skillAthleticsExpertise: false,
    skillDeceptionProficient: false,
    skillDeceptionExpertise: false,
    skillHistoryProficient: true,
    skillHistoryExpertise: false,
    skillInsightProficient: false,
    skillInsightExpertise: false,
    skillIntimidationProficient: false,
    skillIntimidationExpertise: false,
    skillInvestigationProficient: false,
    skillInvestigationExpertise: false,
    skillMedicineProficient: false,
    skillMedicineExpertise: false,
    skillNatureProficient: false,
    skillNatureExpertise: false,
    skillPerceptionProficient: true,
    skillPerceptionExpertise: false,
    skillPerformanceProficient: false,
    skillPerformanceExpertise: false,
    skillPersuasionProficient: false,
    skillPersuasionExpertise: false,
    skillReligionProficient: false,
    skillReligionExpertise: false,
    skillSleightOfHandProficient: false,
    skillSleightOfHandExpertise: false,
    skillStealthProficient: false,
    skillStealthExpertise: false,
    skillSurvivalProficient: true,
    skillSurvivalExpertise: false,
  },
  {
    // id: 'cl6zseh9p0993y6s6wenn5h7e',
    name: 'Mel O. Dyse',
    playerName: 'Tina',
    // createdById: 'cl5or5v160006uts6oqve5l5a',
    // createdAt: '2022-08-19T01:22:41.005Z',
    // updatedAt: '2022-08-19T01:22:41.006Z',
    type: 'pc',
    isFriendly: false,
    isDead: false,
    avatar: '',
    race: 'Tiefling',
    characterClass: 'Bard',
    subclass: '',
    advancementType: 'milestone',
    level: 6,
    experiencePoints: 0,
    hpMax: 33,
    ac: 12,
    spellSave: 14,
    hitDice: null,
    conditions: undefined,
    currentHp: null,
    tempHp: null,
    currentAc: null,
    deathSavesSuccess: null,
    deathSavesFailed: null,
    initiative: 0,
    inspiration: false,
    speedWalking: 30,
    speedClimbing: 0,
    speedFlying: 0,
    speedSwimming: 0,
    speedBurrowing: 0,
    creatureSize: '',
    creatureType: '',
    alignment: '',
    challengeRating: '',
    source: '',
    str: 10,
    strBonus: false,
    dex: 13,
    dexBonus: true,
    con: 11,
    conBonus: false,
    int: 12,
    intBonus: false,
    wis: 13,
    wisBonus: false,
    cha: 17,
    chaBonus: true,
    skillAcrobaticsProficient: false,
    skillAcrobaticsExpertise: false,
    skillAnimalHandlingProficient: false,
    skillAnimalHandlingExpertise: false,
    skillArcanaProficient: false,
    skillArcanaExpertise: false,
    skillAthleticsProficient: false,
    skillAthleticsExpertise: false,
    skillDeceptionProficient: false,
    skillDeceptionExpertise: false,
    skillHistoryProficient: false,
    skillHistoryExpertise: false,
    skillInsightProficient: true,
    skillInsightExpertise: false,
    skillIntimidationProficient: false,
    skillIntimidationExpertise: false,
    skillInvestigationProficient: true,
    skillInvestigationExpertise: false,
    skillMedicineProficient: false,
    skillMedicineExpertise: false,
    skillNatureProficient: false,
    skillNatureExpertise: false,
    skillPerceptionProficient: false,
    skillPerceptionExpertise: false,
    skillPerformanceProficient: true,
    skillPerformanceExpertise: true,
    skillPersuasionProficient: true,
    skillPersuasionExpertise: true,
    skillReligionProficient: false,
    skillReligionExpertise: false,
    skillSleightOfHandProficient: false,
    skillSleightOfHandExpertise: false,
    skillStealthProficient: false,
    skillStealthExpertise: false,
    skillSurvivalProficient: true,
    skillSurvivalExpertise: false,
  },
  {
    // id: 'cl6zsh8961068y6s6x7mxnd9q',
    name: 'Danorin',
    playerName: 'Ben',
    // createdById: 'cl5or5v160006uts6oqve5l5a',
    // createdAt: '2022-08-19T01:24:49.290Z',
    // updatedAt: '2022-08-19T01:24:49.292Z',
    type: 'pc',
    isFriendly: false,
    isDead: false,
    avatar: '',
    race: 'Reborn',
    characterClass: 'Monk',
    subclass: '',
    advancementType: 'milestone',
    level: 6,
    experiencePoints: 0,
    hpMax: 39,
    ac: 15,
    spellSave: 0,
    hitDice: null,
    conditions: undefined,
    currentHp: null,
    tempHp: null,
    currentAc: null,
    deathSavesSuccess: null,
    deathSavesFailed: null,
    initiative: 0,
    inspiration: false,
    speedWalking: 30,
    speedClimbing: 0,
    speedFlying: 0,
    speedSwimming: 0,
    speedBurrowing: 0,
    creatureSize: '',
    creatureType: '',
    alignment: '',
    challengeRating: '',
    source: '',
    str: 12,
    strBonus: true,
    dex: 18,
    dexBonus: true,
    con: 13,
    conBonus: false,
    int: 14,
    intBonus: false,
    wis: 12,
    wisBonus: false,
    cha: 8,
    chaBonus: false,
    skillAcrobaticsProficient: true,
    skillAcrobaticsExpertise: false,
    skillAnimalHandlingProficient: false,
    skillAnimalHandlingExpertise: false,
    skillArcanaProficient: true,
    skillArcanaExpertise: false,
    skillAthleticsProficient: false,
    skillAthleticsExpertise: false,
    skillDeceptionProficient: false,
    skillDeceptionExpertise: false,
    skillHistoryProficient: true,
    skillHistoryExpertise: false,
    skillInsightProficient: true,
    skillInsightExpertise: false,
    skillIntimidationProficient: false,
    skillIntimidationExpertise: false,
    skillInvestigationProficient: false,
    skillInvestigationExpertise: false,
    skillMedicineProficient: false,
    skillMedicineExpertise: false,
    skillNatureProficient: false,
    skillNatureExpertise: false,
    skillPerceptionProficient: false,
    skillPerceptionExpertise: false,
    skillPerformanceProficient: false,
    skillPerformanceExpertise: false,
    skillPersuasionProficient: false,
    skillPersuasionExpertise: false,
    skillReligionProficient: false,
    skillReligionExpertise: false,
    skillSleightOfHandProficient: false,
    skillSleightOfHandExpertise: false,
    skillStealthProficient: false,
    skillStealthExpertise: false,
    skillSurvivalProficient: false,
    skillSurvivalExpertise: false,
  },
  {
    // id: 'cl6zsinc31104y6s6sw2rsvv4',
    name: 'Sindri Ironfist',
    playerName: 'Jon',
    // createdById: 'cl5or5v160006uts6oqve5l5a',
    // createdAt: '2022-08-19T01:25:55.491Z',
    // updatedAt: '2022-08-19T01:25:55.492Z',
    type: 'pc',
    isFriendly: false,
    isDead: false,
    avatar: '',
    race: 'Hill Dwarf',
    characterClass: 'Cleric',
    subclass: '',
    advancementType: 'milestone',
    level: 0,
    experiencePoints: 0,
    hpMax: 51,
    ac: 18,
    spellSave: 0,
    hitDice: null,
    conditions: undefined,
    currentHp: null,
    tempHp: null,
    currentAc: null,
    deathSavesSuccess: null,
    deathSavesFailed: null,
    initiative: 0,
    inspiration: false,
    speedWalking: 30,
    speedClimbing: 0,
    speedFlying: 0,
    speedSwimming: 0,
    speedBurrowing: 0,
    creatureSize: '',
    creatureType: '',
    alignment: '',
    challengeRating: '',
    source: '',
    str: 19,
    strBonus: false,
    dex: 8,
    dexBonus: false,
    con: 15,
    conBonus: false,
    int: 10,
    intBonus: false,
    wis: 19,
    wisBonus: true,
    cha: 12,
    chaBonus: true,
    skillAcrobaticsProficient: false,
    skillAcrobaticsExpertise: false,
    skillAnimalHandlingProficient: false,
    skillAnimalHandlingExpertise: false,
    skillArcanaProficient: false,
    skillArcanaExpertise: false,
    skillAthleticsProficient: true,
    skillAthleticsExpertise: false,
    skillDeceptionProficient: false,
    skillDeceptionExpertise: false,
    skillHistoryProficient: false,
    skillHistoryExpertise: false,
    skillInsightProficient: false,
    skillInsightExpertise: false,
    skillIntimidationProficient: true,
    skillIntimidationExpertise: false,
    skillInvestigationProficient: false,
    skillInvestigationExpertise: false,
    skillMedicineProficient: true,
    skillMedicineExpertise: false,
    skillNatureProficient: false,
    skillNatureExpertise: false,
    skillPerceptionProficient: false,
    skillPerceptionExpertise: false,
    skillPerformanceProficient: false,
    skillPerformanceExpertise: false,
    skillPersuasionProficient: false,
    skillPersuasionExpertise: false,
    skillReligionProficient: true,
    skillReligionExpertise: false,
    skillSleightOfHandProficient: false,
    skillSleightOfHandExpertise: false,
    skillStealthProficient: false,
    skillStealthExpertise: false,
    skillSurvivalProficient: false,
    skillSurvivalExpertise: false,
  },
  {
    // id: 'cl6zsqvnf0015els69uhrijyx',
    name: 'Ireena Kolyana',
    playerName: '',
    // createdById: 'cl5or5v160006uts6oqve5l5a',
    // createdAt: '2022-08-19T01:32:19.515Z',
    // updatedAt: '2022-08-19T01:32:19.515Z',
    type: 'npc',
    isFriendly: false,
    isDead: false,
    avatar: '',
    race: '',
    characterClass: '',
    subclass: '',
    advancementType: 'xp',
    level: 0,
    experiencePoints: 0,
    hpMax: 14,
    ac: 15,
    spellSave: 0,
    hitDice: '2d8',
    conditions: undefined,
    currentHp: null,
    tempHp: null,
    currentAc: null,
    deathSavesSuccess: null,
    deathSavesFailed: null,
    initiative: 0,
    inspiration: false,
    speedWalking: 30,
    speedClimbing: 0,
    speedFlying: 0,
    speedSwimming: 0,
    speedBurrowing: 0,
    creatureSize: 'Medium',
    creatureType: 'Humanoid',
    alignment: 'Lawful Good',
    challengeRating: '1/8',
    source: 'Curse of Strahd',
    str: 11,
    strBonus: false,
    dex: 12,
    dexBonus: false,
    con: 11,
    conBonus: false,
    int: 12,
    intBonus: false,
    wis: 14,
    wisBonus: false,
    cha: 16,
    chaBonus: false,
    skillAcrobaticsProficient: false,
    skillAcrobaticsExpertise: false,
    skillAnimalHandlingProficient: false,
    skillAnimalHandlingExpertise: false,
    skillArcanaProficient: false,
    skillArcanaExpertise: false,
    skillAthleticsProficient: false,
    skillAthleticsExpertise: false,
    skillDeceptionProficient: true,
    skillDeceptionExpertise: false,
    skillHistoryProficient: false,
    skillHistoryExpertise: false,
    skillInsightProficient: true,
    skillInsightExpertise: false,
    skillIntimidationProficient: false,
    skillIntimidationExpertise: false,
    skillInvestigationProficient: false,
    skillInvestigationExpertise: false,
    skillMedicineProficient: false,
    skillMedicineExpertise: false,
    skillNatureProficient: false,
    skillNatureExpertise: false,
    skillPerceptionProficient: false,
    skillPerceptionExpertise: false,
    skillPerformanceProficient: false,
    skillPerformanceExpertise: false,
    skillPersuasionProficient: true,
    skillPersuasionExpertise: false,
    skillReligionProficient: false,
    skillReligionExpertise: false,
    skillSleightOfHandProficient: false,
    skillSleightOfHandExpertise: false,
    skillStealthProficient: false,
    skillStealthExpertise: false,
    skillSurvivalProficient: false,
    skillSurvivalExpertise: false,
  },
  {
    // id: 'cl6zs0rxn0686y6s695h8j11p',
    name: 'Berrian Siannodel',
    playerName: 'Adam',
    // createdById: 'cl5or5v160006uts6oqve5l5a',
    // createdAt: '2022-08-19T01:12:01.643Z',
    // updatedAt: '2022-08-19T01:12:01.644Z',
    type: 'pc',
    isFriendly: false,
    isDead: false,
    avatar: '',
    race: 'High Elf',
    characterClass: 'Wizard',
    subclass: '',
    advancementType: 'xp',
    level: 6,
    experiencePoints: 0,
    hpMax: 36,
    ac: 14,
    spellSave: 15,
    hitDice: null,
    conditions: undefined,
    currentHp: null,
    tempHp: null,
    currentAc: null,
    deathSavesSuccess: null,
    deathSavesFailed: null,
    initiative: 0,
    inspiration: false,
    speedWalking: 30,
    speedClimbing: 0,
    speedFlying: 0,
    speedSwimming: 0,
    speedBurrowing: 0,
    creatureSize: '',
    creatureType: '',
    alignment: '',
    challengeRating: '',
    source: '',
    str: 10,
    strBonus: false,
    dex: 17,
    dexBonus: false,
    con: 14,
    conBonus: false,
    int: 19,
    intBonus: true,
    wis: 12,
    wisBonus: true,
    cha: 8,
    chaBonus: false,
    skillAcrobaticsProficient: false,
    skillAcrobaticsExpertise: false,
    skillAnimalHandlingProficient: false,
    skillAnimalHandlingExpertise: false,
    skillArcanaProficient: true,
    skillArcanaExpertise: false,
    skillAthleticsProficient: false,
    skillAthleticsExpertise: false,
    skillDeceptionProficient: false,
    skillDeceptionExpertise: false,
    skillHistoryProficient: true,
    skillHistoryExpertise: false,
    skillInsightProficient: true,
    skillInsightExpertise: false,
    skillIntimidationProficient: false,
    skillIntimidationExpertise: false,
    skillInvestigationProficient: false,
    skillInvestigationExpertise: false,
    skillMedicineProficient: false,
    skillMedicineExpertise: false,
    skillNatureProficient: false,
    skillNatureExpertise: false,
    skillPerceptionProficient: true,
    skillPerceptionExpertise: false,
    skillPerformanceProficient: false,
    skillPerformanceExpertise: false,
    skillPersuasionProficient: false,
    skillPersuasionExpertise: false,
    skillReligionProficient: true,
    skillReligionExpertise: false,
    skillSleightOfHandProficient: false,
    skillSleightOfHandExpertise: false,
    skillStealthProficient: false,
    skillStealthExpertise: false,
    skillSurvivalProficient: false,
    skillSurvivalExpertise: false,
  },
]
